#!/bin/bash -
echo "DEBUG = True" > app/local_settings.py
echo "SECRET_KEY = \"$(cat /dev/urandom | env LC_CTYPE=C tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)\"" >> app/local_settings.py
echo "NEVERCACHE_KEY = \"$(cat /dev/urandom | env LC_CTYPE=C tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)\"" >> app/local_settings.py
docker-compose build
